### ISSUE TITLE
Compiling OpenMM on Titan with CUDA 7.5

### ISSUE THREAD

**Issue by jchodera** [radical-collaboration/MSKCC#3]
@jdakka : I'd give OpenMM 6.3.1 a try first, since I believe that is built against CUDA 7.5.
After you've installed [miniconda Python](https://conda.io/miniconda.html), you can
```bash
conda config --add channels omnia --add channels conda-forge
conda install --yes openmm==6.3.1
```
If you run our benchmark script, you should see it mention that it is using the `CUDA` platform. If it says `OpenCL` or `CPU`, it's not able to use your CUDA libraries for some reason. You can check which platforms are available with
```python
>>> from simtk import openmm
>>> print([openmm.Platform.getPlatform(index).getName() for index in range(openmm.Platform.getNumPlatforms())])
['Reference', 'CPU', 'OpenCL']
```
(my mac doesn't have `CUDA` available)

If you need to build from OpenMM from source for CUDA 7.5, you should be able to follow the instructions [here](http://docs.openmm.org/7.1.0/userguide/index.html) on compiling OpenMM from source using CUDA 7.5 installed on Titan. Be sure to pay attention to the dependencies.

It's best to install [miniconda Python](https://conda.io/miniconda.html) first anyway, since we can use that to easily install other dependencies for our scripts if needed. (We've tried to minimize dependencies in this initial benchmark script, but future elaborations will require more conda-installable dependencies.)

I've tried to save you some pain by building a conda-installable OpenMM built against CUDA 7.5, but no luck so far.

**Comment by jdakka** [comment]
@jchodera I figured out the issue but OpenMM 7.2/cuda75 won't install with the command you provided. I was able to install OpenMM 6.3 and OpenMM 7.1 but during execution it latched to the CPU instead, even though it recognized CUDA as well. 

PackageNotFoundError: Package not found: Conda could not find '

**Comment by shantenujha** [comment]
@jdakka @jchodera Maybe it is better to take this problem to the OpenMM mailing list, rather than have @jchodera troubleshoot?

**Comment by jchodera** [comment]
No need, @pgrinaway and I are the right people to support this, though I was stuck in a meeting all day. Give me a moment to find the issue.

**Comment by jchodera** [comment]
Here's the syntax to use:
```
conda remove --yes openmm
conda clean -plti ---yes
conda install ---yes -c omnia/label/cuda75 openmm
```
If this doesn't install OpenMM 7.2 from the cuda75 label, let me know what it prints as output.

Thanks so much for being our hands and eyes in working through the OpenMM benchmarking issues!

**Comment by jdakka** [comment]
@jchodera it installs the package but I'm not seeing the correct version that you have nor and cuda75 label...
`conda install -c omnia/label/cuda75 openmm
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /ccs/proj/csc230/mskcc/miniconda/envs/venv:

The following NEW packages will be INSTALLED:

    openmm: 7.1.1-py27_0 omnia`

**Comment by jchodera** [comment]
I think I know what happened: The package must have been routed to the wrong label and then overwritten by our nightly dev builds. Let me fix that. Will take about an hour. Apologies again!

**Comment by jchodera** [comment]
OK, try this:
```
conda remove --yes openmm
conda clean -plti --yes
conda install -c omnia/label/dev --yes openmm-cuda75
```

**Comment by jdakka** [comment]
Success! Quite a few environmental setup hurdles but it's working (I'll write a formal set of instructions in the READ.me for Titan specifically)

```
(venv) jdakka@titan-batch8:/lustre/atlas/proj-shared/csc230/mskcc/MSKCC/abl-imatinib-benchmark> aprun -n1 python benchmark.py
['Reference', 'CPU', 'CUDA', 'OpenCL']
Deserializing simulation...
System contains 46648 atoms.
Using platform "CUDA".
Initial potential energy is -141208.481 kcal/mol
Warming up integrator to trigger kernel compilation...
Benchmarking...
completed     5000 steps in   22.567 s : performance is   38.286 ns/day
Final potential energy is -141316.976 kcal/mol
Application 14507233 resources: utime ~49s, stime ~6s, Rss ~350156, inblocks ~315692, outblocks ~69481
```

**Comment by jchodera** [comment]
Huzzah!

If we want to benchmark the [systems mentioned in the NAMD issue here](https://github.com/radical-collaboration/INCITE-2017/issues/1) too, I can add those as well.

**Comment by shantenujha** [comment]
@jchodera -- you're my hero! truly impressed.
